### ISSUE TITLE
Pt-BR Translation

### ISSUE THREAD

**Issue by Mendelyeev** [mpdifran/Memento-Issues#27]
Dear, I really loved your app. But i noticied that brazilian portuguese translation is not so good (seems like was translated by google translator). If you want, I can help in that translation.

**Comment by mpdifran** [comment]
Awesome! Send me an email at betterremindersapp@gmail.com and I can send you the current localization files! I believe initially a volunteer provided the translations, but I've probably used Google Translate to fill in the gaps.

**Comment by Mendelyeev** [comment]
Right!!

Sent! 🙂
