### ISSUE TITLE
Heritage Version for Catalina?

### ISSUE THREAD

**Issue by mkaufhh** [mpdifran/Memento-Issues#36]
Hi, is it possible to get a heritage version of Memento that runs on my Catalina Mac? This machine can't be updated to Big Sur and I'd really love to use Memento (so much so that I'd also pay for a heritage version).

Thanks!

**Comment by mpdifran** [comment]
Thanks for the suggestion! I can look into it but I believe the minimum version was explicitly set to Big Sur for a technical reason. I'll post back here when I've verified!

**Comment by mkaufhh** [comment]
Thanks a lot!

**Comment by mpdifran** [comment]
Hey, sorry for the delay on this! 

I've confirmed that there's technical reasons for not supporting below macOS 11 (Big Sur).

**Comment by mkaufhh** [comment]
Mark, thanks for trying anyway!
