### ISSUE TITLE
Ventura

### ISSUE THREAD

**Issue by rdebeau** [mpdifran/Memento-Issues#64]
Upgraded to Mac Ventura.  Getting an error on launching Memento "Error, There was an issue retrieving your reminder lists from your device".

**Comment by mpdifran** [comment]
I noticed this as well, I'm looking into it and will hopefully have a fix soon.

**Comment by cameronbensimon** [comment]
Same issue

**Comment by chris-the-nerd** [comment]
Also on M1/Ventura and getting the same issue.

**Comment by chris-the-nerd** [comment]
> I noticed this as well, I'm looking into it and will hopefully have a fix soon.

Any update on this issue @mpdifran ?

**Comment by mpdifran** [comment]
I have a fix in place, just need to do an official release. In the meantime, you can use the fix [on TestFlight](https://testflight.apple.com/join/aRvubPov).

**Comment by mpdifran** [comment]
I've submitted to the App Store for review, version 4.1 should be out imminently!
