### ISSUE TITLE
Things become un-interactable until app crashes and restarts on iOS app

### ISSUE THREAD

**Issue by pettazz** [mpdifran/Memento-Issues#67]
**Info:**
 Device: iPhone 14 Pro
 OS: iOS 16.3
 Memento Version 4.1

**Describe the bug**
When adding items to a list with a Location alert, after switching away or locking/unlocking phone, no longer able to add or edit items (tapping + or list items does nothing, including check complete), can go back to Lists menu but then cannot view another list, eventually the app crashes and restarts, cycle starts over.

Also unable to tap to add new or edit existing Location Alerts on lists, tapping the Location button in Details simply has no effect.

All permissions granted, Location set to "always"

**Comment by mpdifran** [comment]
Hmm this is very odd. Do you happen to have a large number of reminders (specifically completed reminders). There's a utility to delete completed reminders in the list details in Memento, but you can also check in Apple's Reminders app if you're having trouble in Memento.

**Comment by pettazz** [comment]
Ah I hadn't thought of that, I just deleted a few thousand old ones (could we get an option to auto-delete completed tasks?). But it does still seem to be behaving the same. I even deleted and reinstalled the app, same behavior.

**Comment by mpdifran** [comment]
Are there any issues using / modifying these reminders in Apple's app? Is there anything unusual configured for that list that causes the crash?

**Comment by pettazz** [comment]
No, they seem to work fine in Reminders. And nothing odd as far as I can tell, except that it seems to be related to Location alerts. If I try to add a new list or edit an existing one, tapping the Location button in the details does nothing at all. Permissions are set to always with precise enabled. Also, notifications always work completely fine, it's just navigating in the app where I run into issues.

**Comment by mpdifran** [comment]
Hmm this is super weird. Maybe try disabling location permissions, and trying to set a location alarm? That will execute a separate code path, and may help you get around the crash when you re-enable it.

**Comment by pettazz** [comment]
I think this worked! I did this on my multiple location alert lists and have now been using it for about a week without any of the previously mentioned issues. Thank you so much!
