### ISSUE TITLE
Feature request: Improve the AM/PM alarm selection in time alert

### ISSUE THREAD

**Issue by johngarciava** [mpdifran/Memento-Issues#70]
When creating a note, for the time alert option, the AM/PM option is currently a scroll. I think it should be tappable like the overall date one is with the calendar. Tapping is just so much better to work with. I've seen other reminder apps display a whole clock, this app should do the same if possible, something like [this](https://i.imgur.com/mFpbWBd.jpg.)

Continuing with the tapping theme, I think for the repeat option, it shouldn't be a scroll either, the options should be all laid out and you just tap the one you want, it's already a big box so all the options should fit pretty easily.

**Comment by mpdifran** [comment]
Hey, thanks for the suggestion! 

Unfortunately I'm leveraging iOS' date and time pickers, so I don't have any ability to customize the UI here. Date and time logic is extremely complex, so as a solo dev, I can save a bunch of time by using iOS' built in pickers, and spend that time on other features. Sorry about that!
