### ISSUE TITLE
Widget dysfunction in iOS 17.0

### ISSUE THREAD

**Issue by balagger** [mpdifran/Memento-Issues#72]
**Info:**
 Device: iPhone 14 Pro
 OS: iOS 17.0 public beta 1
 Memento Version 4.1(76)

**Describe the bug**
Widgets on Lock Screen and Home Screen display error imaging

https://github.com/mpdifran/Memento-Issues/assets/140748787/28a49e6c-cc52-4fbd-a099-32fc126b6d24

**Comment by mpdifran** [comment]
I've fixed this in the latest TestFlight build! Install 4.2 (89) or newer and the problem should be solved.
