### ISSUE TITLE
Biweekly Reminders Don’t Repeat in Memento

### ISSUE THREAD

**Issue by rcavin** [mpdifran/Memento-Issues#73]
**Info:**
 Device: iPhone SE 2
 OS: iOS 17.2.1
 Memento Version: 4.2

**Describe the bug**
Several reminders set to repeat every 2 weeks do not show up as repeating in Memento. Other weekly repeating events show up as weekly repeating in Memento.

**Expected behavior**
Expect the repeating schedules to match.

**Screenshots**

**Comment by mpdifran** [comment]
Hmm that's super weird. I just tried to set up a biweekly reminder on my device, and it seemed to work fine. Also really odd that you're seeing other repeating reminders work properly. Do you have screenshots of what you're seeing when you set it up to repeat every 2 weeks?

![Memento](https://github.com/mpdifran/Memento-Issues/assets/1365987/fd6c359d-d28e-479b-950b-593e17cdadae)

**Comment by rcavin** [comment]
Hi Mark,
Here’s what I’m seeing:

I haven’t tried creating new biweekly recurring events, but these existed
when I launched Memento.
Thanks,
Bob

**Comment by rcavin** [comment]
Ah, the issue seems to be the biweekly events have no time associated with
them. When I added a time in Reminders, the biweekly showed up in Memento.

**Comment by mpdifran** [comment]
Ah makes sense! Some apps just set a date and no time, and use a default time to set the alarm. I'll look into adding something similar for Memento in the future!

**Comment by rcavin** [comment]
For what it’s worth, the reminders with no designated time show up at 12am
on the Siri watch face and don’t send notifications, which is how I like
them appearing, i.e. things I’d like to get to on a particular day, but not
be notified about. Turns out even non-repeating reminders with a set date
and no time don’t appear in Memento on the set date. This makes Memento
less useful to me, but I like the design, so I’ll hang onto it and keep an
eye out for updates. Appreciate the troubleshooting, Mark. The reviews were
spot on about you being a responsive developer.
Thanks,
Bob

**Comment by mpdifran** [comment]
Thanks for the details, definitely something I'll prioritize!
