### ISSUE TITLE
App Crashing After Completing Reminders

### ISSUE THREAD

**Issue by alexferrigno** [mpdifran/Memento-Issues#77]
**Info:**
 Device: iPhone 14 Pro
 OS: iOS 18.1
 Memento Version 4.4.1

**Describe the bug**
After marking a reminder as complete, and then tapping anywhere else in the app, the app instantly crashes and closes. This has been occurring for at least a month or so if I am remembering correctly, and so I have had to resort to completing reminders in Fantastical instead. 

**Expected behavior**
No crashes after completing reminders. 

**Screenshots**
No screenshots but happy to provide a screen recording if that would help?

**Comment by mpdifran** [comment]
Hey, thanks for submitting! I noticed that crash as well, but it should be fixed in version 4.4.1. Very odd that it's still happening. A video would be great!

**Comment by alexferrigno** [comment]
Hey there,

Thanks for the super quick reply! 

I just tried again and have found out that it only seems to happen with past-due reminders, and not ones which have not yet become due/late. 

First recording shows everything fine with a test reminder a few minutes in the future but second recording shows the crash with one that has become due. 

Hope this helps, but please let me know anything else would be useful of course! 

[removed videos 28.11.24]

**Comment by mpdifran** [comment]
Thank you for the details! The latest version of Memento (4.4.5) should fix this crash. Please let me know if you still see it!
